language: rust
rust:
  - stable
before_install:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt -- --check